#!/bin/sh

# Called by sxiv(1) whenever an image gets loaded.
# The output is displayed in sxiv's status bar.
# Arguments:
#   $1: path to image file
#   $2: image width
#   $3: image height

s="  "	# field separator

exec 2>/dev/null	# show no errors on output

filesize=$(du -Hh -- "$1" | cut -f 1)
geometry="${2}x${3}"
filename=${1##*/}

echo "${filename}${s}${geometry}${s}${filesize}"
